Lab1_Ryzhickov
NataRazmochaeva/PiAA_8304 pull request #12
Opened 2020-03-05 10:56 UTC by AlexRyzhickov

2020-03-05 11:16 UTC, AlexRyzhickov commented
Вариант 2и

2020-03-05 12:34 UTC, NataRazmochaeva requested changes
1) Форматирование отчета: http://se.moevm.info/doku.php/courses:informatics:reportrules
2) Описать реализованные функции (что на вход, что на выход -- описать)
3) проверить форматирование титульного листа

2020-03-20 09:58 UTC, AlexRyzhickov commented
Отчёт отформатирован
добавлен Last_report.doc
добавлен Last_report.pdf

2020-03-26 10:58 UTC, NataRazmochaeva commented
Надо удалить лишние pdf-файлы

2020-03-26 11:51 UTC, NataRazmochaeva commented
Удалить лишние файлы из PR для ЛР-2

2020-03-26 11:54 UTC, NataRazmochaeva approved these changes

2020-03-26 11:54 UTC, merged