Ryzhickov Alexander lab2
NataRazmochaeva/PiAA_8304 pull request #28
Opened 2020-03-20 09:24 UTC by AlexRyzhickov

2020-03-26 11:12 UTC, NataRazmochaeva requested changes
Я могу смержить первую ЛР как есть (с лишними pdf-файлами), но тогда для мержа второй я попрошу Вас убрать лишние pdf-файлы. Напишите, из какого PR Вам удобнее убирать лишние файлы. 
* вынести код из main в отдельные функции (обновить в PR, также в коде можно оставить отладочный вывод)
* если есть классы, добавьте в папку UML, описывающие ваши классы

2020-03-26 12:21 UTC, AlexRyzhickov commented
Uml добавил, лишние файлы удалил

2020-03-26 13:01 UTC, AlexRyzhickov commented
Можно мержить

2020-04-09 11:03 UTC, NataRazmochaeva approved these changes

2020-04-09 11:03 UTC, merged