Cheshuin_Dmitry_lab1
NataRazmochaeva/PiAA_8304 pull request #66
Opened 2020-04-21 23:29 UTC by Wintari

2020-04-22 18:56 UTC, Wintari commented
@NataRazmochaeva

2020-04-23 10:58 UTC, NataRazmochaeva requested changes
Замечания по отчету:
1. Подпись таблиц -- Таблица 1 <тире> Название таблицы с большой буквы без точки в конце
Название таблицы располагается над таблицей слева -- *проверьте*
2. Название рисунков: Рисунок 1 <тире> Название рисунка с большой буквы без точки в конце
Располагается под рис. по центру (у Вас правильно)
Да, в Word для названий объектов (таблиц и рисунков) один стиль, но, к сожалению, надо его корректировать его отдельно. 
Код
1. Пофиксить кодировку в комментариях

2020-04-23 10:58 UTC, NataRazmochaeva commented on Cheshuin_Dmitry/Lab1/main.cpp
> +            //��������� ����� �����
Кодировка слетела

2020-04-23 11:36 UTC, Wintari commented
Исправлено.

> Замечания по отчету:
> 
> 1. Подпись таблиц -- Таблица 1 <тире> Название таблицы с большой буквы без точки в конце
>    Название таблицы располагается над таблицей слева -- _проверьте_
> 2. Название рисунков: Рисунок 1 <тире> Название рисунка с большой буквы без точки в конце
>    Располагается под рис. по центру (у Вас правильно)
>    Да, в Word для названий объектов (таблиц и рисунков) один стиль, но, к сожалению, надо его корректировать его отдельно.
>    Код
> 3. Пофиксить кодировку в комментариях

Исправлено,

2020-04-23 11:36 UTC, Wintari commented
Добавлен ввод/вывод из файлов с помощью аргументов командой строки.

2020-04-23 11:40 UTC, NataRazmochaeva approved these changes

2020-04-23 11:40 UTC, merged