Ivchenko_Anton_lr1
NataRazmochaeva/PiAA_8304 pull request #67
Opened 2020-04-22 16:27 UTC by scissorsnatcher

2020-04-28 12:50 UTC, NataRazmochaeva requested changes
Отчет:
1. Приложение  с кодом
2. Подписать картинки с тестированием
3. Проверить размеры шрифтов

2020-04-28 12:53 UTC, NataRazmochaeva requested changes
Формулировку варианта (прям из письма преподавателя) добавьте в отчет.

2020-04-30 12:11 UTC, scissorsnatcher commented
Ссылка на первый pr https://github.com/NataRazmochaeva/PiAA_8304/pull/51

2020-05-21 14:42 UTC, NataRazmochaeva approved these changes
Первый пулл реквест был вовремя

2020-05-21 14:42 UTC, merged